argocd:
  host: "port-forward"
  namespace: "argocd"
  username: "admin"
  insecure: false # Skip server certificate and domain verification
  grpcweb: false
  plaintext: true # Disable TLS
  port-forward: true # Connect to a random argocd-server port using port forwarding
