= ArTUI

 $$$$$$\         $$$$$$$$\ $$\   $$\ $$$$$$\ 
$$  __$$\        \__$$  __|$$ |  $$ |\_$$  _|
$$ /  $$ | $$$$$$\  $$ |   $$ |  $$ |  $$ |  
$$$$$$$$ |$$  __$$\ $$ |   $$ |  $$ |  $$ |  
$$  __$$ |$$ |  \__|$$ |   $$ |  $$ |  $$ |  
$$ |  $$ |$$ |      $$ |   $$ |  $$ |  $$ |  
$$ |  $$ |$$ |      $$ |   \$$$$$$  |$$$$$$\ 
\__|  \__|\__|      \__|    \______/ \______|

                                        
  ,---.         ,--------.,--. ,--.,--. 
 /  O  \ ,--.--.'--.  .--'|  | |  ||  | 
|  .-.  ||  .--'   |  |   |  | |  ||  | 
|  | |  ||  |      |  |   '  '-'  '|  | 
`--' `--'`--'      `--'    `-----' `--' 

     _        _____ _   _ ___ 
    / \   _ _|_   _| | | |_ _|
   / _ \ | '__|| | | | | || | 
  / ___ \| |   | | | |_| || | 
 /_/   \_\_|   |_|  \___/|___|
                              
_______       ____________  _________
___    |_________  __/_  / / /___  _/
__  /| |_  ___/_  /  _  / / / __  /  
_  ___ |  /   _  /   / /_/ / __/ /   
/_/  |_/_/    /_/    \____/  /___/   
                                     

      .o.                ooooooooooooo ooooo     ooo ooooo 
     .888.               8'   888   `8 `888'     `8' `888' 
    .8"888.     oooo d8b      888       888       8   888  
   .8' `888.    `888""8P      888       888       8   888  
  .88ooo8888.    888          888       888       8   888  
 .8'     `888.   888          888       `88.    .8'   888  
o88o     o8888o d888b        o888o        `YbodP'    o888o 
                                                           
                                                           
   _____         ___________ ____ ___ .___  
  /  _  \ _______\__    ___/|    |   \|   | 
 /  /_\  \\_  __ \ |    |   |    |   /|   | 
/    |    \|  | \/ |    |   |    |  / |   | 
\____|__  /|__|    |____|   |______/  |___| 
        \/                                  

   #           ####### #     # ### 
  # #   #####     #    #     #  #  
 #   #  #    #    #    #     #  #  
#     # #    #    #    #     #  #  
####### #####     #    #     #  #  
#     # #   #     #    #     #  #  
#     # #    #    #     #####  ###


    |             |''||''| '||'  '|' '||' 
   |||    ... ..     ||     ||    |   ||  
  |  ||    ||' ''    ||     ||    |   ||  
 .''''|.   ||        ||     ||    |   ||  
.|.  .||. .||.      .||.     '|..'   .||. 
                                          

   _____       _______________ ___.___ 
  /  _  \______\__    ___/    |   \   |
 /  /_\  \_  __ \|    |  |    |   /   |
/    |    \  | \/|    |  |    |  /|   |
\____|__  /__|   |____|  |______/ |___|
        \/                             

 ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄         ▄  ▄▄▄▄▄▄▄▄▄▄▄ 
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░▌       ▐░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀█░█▀▀▀▀ ▐░▌       ▐░▌ ▀▀▀▀█░█▀▀▀▀ 
▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     ▐░▌       ▐░▌     ▐░▌     
▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌     ▐░▌     ▐░▌       ▐░▌     ▐░▌     
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░▌       ▐░▌     ▐░▌     
▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀█░█▀▀      ▐░▌     ▐░▌       ▐░▌     ▐░▌     
▐░▌       ▐░▌▐░▌     ▐░▌       ▐░▌     ▐░▌       ▐░▌     ▐░▌     
▐░▌       ▐░▌▐░▌      ▐░▌      ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌ ▄▄▄▄█░█▄▄▄▄ 
▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
 ▀         ▀  ▀         ▀       ▀       ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀ 
                                                                 

   █████████             ███████████ █████  █████ █████
  ███░░░░░███           ░█░░░███░░░█░░███  ░░███ ░░███ 
 ░███    ░███  ████████ ░   ░███  ░  ░███   ░███  ░███ 
 ░███████████ ░░███░░███    ░███     ░███   ░███  ░███ 
 ░███░░░░░███  ░███ ░░░     ░███     ░███   ░███  ░███ 
 ░███    ░███  ░███         ░███     ░███   ░███  ░███ 
 █████   █████ █████        █████    ░░████████   █████
░░░░░   ░░░░░ ░░░░░        ░░░░░      ░░░░░░░░   ░░░░░ 
                                                       
                                                       
       d8888     88888888888 888     888 8888888 
      d88888         888     888     888   888   
     d88P888         888     888     888   888   
    d88P 888 888d888 888     888     888   888   
   d88P  888 888P"   888     888     888   888   
  d88P   888 888     888     888     888   888   
 d8888888888 888     888     Y88b. .d88P   888   
d88P     888 888     888      "Y88888P"  8888888 
                                                 
                                                 
             _______ _    _ _____ 
     /\     |__   __| |  | |_   _|
    /  \   _ __| |  | |  | | | |  
   / /\ \ | '__| |  | |  | | | |  
  / ____ \| |  | |  | |__| |_| |_ 
 /_/    \_\_|  |_|   \____/|_____|
                                  
 █████╗ ██████╗ ████████╗██╗   ██╗██╗
██╔══██╗██╔══██╗╚══██╔══╝██║   ██║██║
███████║██████╔╝   ██║   ██║   ██║██║
██╔══██║██╔══██╗   ██║   ██║   ██║██║
██║  ██║██║  ██║   ██║   ╚██████╔╝██║
╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝
                                     
░▒▓█ ArTUI - Managing ArgoCD █▓▒░

▁ ▂ ▄ ▅ ▆ ▇ █ ArTUI - Managing ArgoCD █ ▇ ▆ ▅ ▄ ▂ ▁

▀▄▀▄▀▄ ArTUI - Managing ArgoCD ▄▀▄▀▄▀

ıllıllı ArTUI - Managing ArgoCD ıllıllı

★彡 ArTUI - Managing ArgoCD 彡★

★·.·´¯`·.·★ ArTUI - Managing ArgoCD ★·.·´¯`·.·★

╚»★«╝ ArTUI - Managing ArgoCD ╚»★«╝

╚» ★ ArTUI - Managing ArgoCD ★ «╝

A program (eventually) for managing ArgoCD Applications.

== Keybindings

=== artui

* ?             = help
* :             = command input

Not sure if I need to login to argo for these

* :refresh      = refresh app
* :hard-refresh = hard refresh app
* :sync         = sync app
* :yaml         = show app raw yaml


=== List

* filter = /
* up     = j
* down   = k

=== Viewport

* top     = home
* bottom  = end
* pgup    = pgup
* up      = arrow
* pgdown  = pgdown
* down    = arrow


== TODO

=== Priority

* [ ] application configuration (file and/or flags)
* [ ] loading screen
* [x] keybindings
* [x] split modules so they can be updated separately and take focus
* [x] use argocd code to generate k8s code for working with argo custom resources
* [ ] perform argo cd actions 
  * [ ] refresh
  * [ ] hard refresh
  * [ ] sync
  * [ ] remove finalizers, delete app, etc. 
  * [ ] manage ssh keys
  * [ ] manage gpg keys
  * [ ] manage repos
* [ ] view application metrics (based on resources in application object)

=== Someday 

* [ ] theme
* [ ] customize key bindings



== References

* https://pkg.go.dev/github.com/argoproj/argo-cd/v2@v2.2.5/pkg/apiclient/session
* https://pkg.go.dev/github.com/argoproj/argo-cd/v2@v2.2.5/pkg/apis/application/v1alpha1
* https://github.com/argoproj-labs/argocd-image-updater/blob/89daab684fcdac4c4d3a0683fe4764a9c1abd0b4/go.mod[go.mod replace examples^]
* https://github.com/argoproj-labs/argocd-image-updater/blob/89daab684fcdac4c4d3a0683fe4764a9c1abd0b4/pkg/argocd/argocd.go[example of connecting to argocd]


