name: build 
on: 
  push:
    branches-ignore:
      - main

jobs:
  # TODO add job for golangci-lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5

      - name: checkout code
        uses: actions/checkout@v3

      - name: build
        run: go build -o ~/release/artui-linux-amd64
