name: build-release 
on: 
  push:
    branches:
      - '!main'
      - '*'
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5

      - name: checkout code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m

      - name: build
        env:
          date: ${{ steps.date.outputs.date }}
        run: go build -ldflags "-X github.com/larntz/artui/cobra/cmd.version=$GITHUB_REF_NAME -X github.com/larntz/artui/cobra/cmd.date=$date -X github.com/larntz/artui/cobra/cmd.hash=$GITHUB_SHA" -o ~/release/artui-linux-amd64
