name: build-release 
on: 
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5

      - name: checkout code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m

      - name: Set DATE environment variable
        run: echo "DATE=$(date +%Y%m%d@%H:%M)" >> $GITHUB_ENV

      - name: build
        env:
          date: ${{ github.event.created_at }}
        run: go build -ldflags "-X github.com/larntz/artui/cobra/cmd.version=$GITHUB_REF_NAME -X github.com/larntz/artui/cobra/cmd.date=${{ env.DATE }} -X github.com/larntz/artui/cobra/cmd.hash=$GITHUB_SHA" -o artui-linux-amd64

      - name: tar gzip
        run: tar -czf artui-linux-amd64.tar.gz LICENSE.md artui-linux-amd64

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        env: 
          release: "${{ github.GITHUB_REF_NAME }}"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            artui-linux-amd64.tar.gz
